# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from descarteslabs.common.proto.vektorius import vektorius_pb2 as descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2


class VektoriusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSchema = channel.unary_unary(
                '/descarteslabs.vektorius.v1.Vektorius/GetSchema',
                request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaRequest.SerializeToString,
                response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaResponse.FromString,
                )
        self.Search = channel.unary_stream(
                '/descarteslabs.vektorius.v1.Vektorius/Search',
                request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchRequest.SerializeToString,
                response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResponse.FromString,
                )
        self.SearchStatus = channel.unary_unary(
                '/descarteslabs.vektorius.v1.Vektorius/SearchStatus',
                request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusRequest.SerializeToString,
                response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusResponse.FromString,
                )
        self.SearchResults = channel.unary_stream(
                '/descarteslabs.vektorius.v1.Vektorius/SearchResults',
                request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsRequest.SerializeToString,
                response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsResponse.FromString,
                )


class VektoriusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VektoriusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaRequest.FromString,
                    response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaResponse.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchRequest.FromString,
                    response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResponse.SerializeToString,
            ),
            'SearchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchStatus,
                    request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusRequest.FromString,
                    response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusResponse.SerializeToString,
            ),
            'SearchResults': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchResults,
                    request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsRequest.FromString,
                    response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'descarteslabs.vektorius.v1.Vektorius', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vektorius(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/descarteslabs.vektorius.v1.Vektorius/GetSchema',
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaRequest.SerializeToString,
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/descarteslabs.vektorius.v1.Vektorius/Search',
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchRequest.SerializeToString,
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/descarteslabs.vektorius.v1.Vektorius/SearchStatus',
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusRequest.SerializeToString,
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/descarteslabs.vektorius.v1.Vektorius/SearchResults',
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsRequest.SerializeToString,
            descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
