# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from descarteslabs.common.proto.vektorius import vektorius_pb2 as descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2


class VektoriusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSchema = channel.unary_unary(
        '/descarteslabs.vektorius.v1.Vektorius/GetSchema',
        request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaRequest.SerializeToString,
        response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/descarteslabs.vektorius.v1.Vektorius/Search',
        request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchRequest.SerializeToString,
        response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResponse.FromString,
        )
    self.SearchStatus = channel.unary_unary(
        '/descarteslabs.vektorius.v1.Vektorius/SearchStatus',
        request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusRequest.SerializeToString,
        response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusResponse.FromString,
        )
    self.SearchResults = channel.unary_stream(
        '/descarteslabs.vektorius.v1.Vektorius/SearchResults',
        request_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsRequest.SerializeToString,
        response_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsResponse.FromString,
        )


class VektoriusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSchema(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchResults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VektoriusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSchema': grpc.unary_unary_rpc_method_handler(
          servicer.GetSchema,
          request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaRequest.FromString,
          response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SchemaResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchRequest.FromString,
          response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResponse.SerializeToString,
      ),
      'SearchStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SearchStatus,
          request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusRequest.FromString,
          response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchStatusResponse.SerializeToString,
      ),
      'SearchResults': grpc.unary_stream_rpc_method_handler(
          servicer.SearchResults,
          request_deserializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsRequest.FromString,
          response_serializer=descarteslabs_dot_common_dot_proto_dot_vektorius_dot_vektorius__pb2.SearchResultsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'descarteslabs.vektorius.v1.Vektorius', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
