#!/bin/bash

SRC=$1
DEST=$2

directories=(descarteslabs descarteslabs/_dl_modules descarteslabs/_dl_modules/client descarteslabs/_dl_modules/client/services descarteslabs/_dl_modules/common descarteslabs/_dl_modules/common/services)
core_pkgs=(auth config)
client_pkgs=(catalog discover scenes tables workflows)
services_pkgs=(catalog metadata places raster service storage tasks vector)
common_pkgs=(discover dltile dotdict http property_filtering proto retry registry services/tasks shapely_support tasks threading)
excludes="--exclude='*.pyc' --exclude=__pycache__ --exclude=BUILD --exclude=tests_internal"

rm -rf $DEST
mkdir $DEST
for d in ${directories[@]}; do
    mkdir $DEST/$d
    # this may get overwritten by rsync below but make sure it always exists
    touch $DEST/$d/__init__.py
    echo $DEST/$d
done

rsync -av $excludes $SRC/descarteslabs/*.py $DEST/descarteslabs
for c in ${core_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/$c $DEST/descarteslabs
done
rsync -av $excludes $SRC/descarteslabs/client/*.py $DEST/descarteslabs/_dl_modules/client
rsync -av $excludes $SRC/descarteslabs/client/auth $DEST/descarteslabs/_dl_modules/client
for s in ${services_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/client/services/$s $DEST/descarteslabs/_dl_modules/client/services
done
for c in ${common_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/common/$c/ $DEST/descarteslabs/_dl_modules/common/$c
done
for c in ${client_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/$c $DEST/descarteslabs/_dl_modules
done
rsync -av $excludes $SRC/descarteslabs/client/packaging/{*.py,README.md} $DEST
# mv -f $DEST/descarteslabs_init.py $DEST/__init__.py