#!/bin/bash

SRC=$1
DEST=$2

directories=(descarteslabs descarteslabs/_dl_modules descarteslabs/_dl_modules/client descarteslabs/_dl_modules/client/services descarteslabs/_dl_modules/common)
services_pkgs=(metadata raster service)
common_pkgs=(dltile dotdict http property_filtering shapely_support threading)
excludes="--exclude='*.pyc' --exclude=__pycache__ --exclude=BUILD --exclude=tests_internal"

rm -rf $DEST
mkdir $DEST
for d in ${directories[@]}; do
    mkdir $DEST/$d
    # this may get overwritten by rsync below but make sure it always exists
    touch $DEST/$d/__init__.py
    echo $DEST/$d
done

rsync -av $excludes $SRC/descarteslabs/client/packaging/descarteslabs_init.py $DEST/descarteslabs/__init__.py
rsync -av $excludes $SRC/descarteslabs/client/*.py $DEST/descarteslabs/_dl_modules/client
rsync -av $excludes $SRC/descarteslabs/client/auth $DEST/descarteslabs/_dl_modules/client
for s in ${services_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/client/services/$s $DEST/descarteslabs/_dl_modules/client/services
done
for c in ${common_pkgs[@]}; do
  rsync -av $excludes $SRC/descarteslabs/common/$c $DEST/descarteslabs/_dl_modules/common
done
rsync -av $excludes $SRC/descarteslabs/scenes $DEST/descarteslabs/_dl_modules
rsync -av $excludes $SRC/descarteslabs/client/packaging/{*.py,README.md} $DEST
