# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xyz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2
from . import errors_pb2 as errors__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xyz.proto',
  package='descarteslabs.workflows',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\txyz.proto\x12\x17\x64\x65scarteslabs.workflows\x1a\x0btypes.proto\x1a\x0c\x65rrors.proto\"\x80\x02\n\x03XYZ\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x02 \x01(\x03\x12\x19\n\x11updated_timestamp\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x31\n\x04type\x18\t \x01(\x0e\x32#.descarteslabs.workflows.ResultType\x12\x0f\n\x07\x63hannel\x18\n \x01(\t\x12\x18\n\x10serialized_graft\x18\x15 \x01(\t\x12\x1b\n\x13serialized_typespec\x18\x16 \x01(\t\x12\x0c\n\x04user\x18\x17 \x01(\t\x12\x0b\n\x03org\x18\x18 \x01(\t\"=\n\x10\x43reateXYZRequest\x12)\n\x03xyz\x18\x01 \x01(\x0b\x32\x1c.descarteslabs.workflows.XYZ\"\x1f\n\rGetXYZRequest\x12\x0e\n\x06xyz_id\x18\x01 \x01(\t\"Y\n\x1aGetXYZSessionErrorsRequest\x12\x0e\n\x06xyz_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x17\n\x0fstart_timestamp\x18\x03 \x01(\x03\"t\n\x08XYZError\x12\x30\n\x04\x63ode\x18\x01 \x01(\x0e\x32\".descarteslabs.workflows.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x12\n\nsession_id\x18\x04 \x01(\t2\xa5\x02\n\x06XYZAPI\x12V\n\tCreateXYZ\x12).descarteslabs.workflows.CreateXYZRequest\x1a\x1c.descarteslabs.workflows.XYZ\"\x00\x12P\n\x06GetXYZ\x12&.descarteslabs.workflows.GetXYZRequest\x1a\x1c.descarteslabs.workflows.XYZ\"\x00\x12q\n\x13GetXYZSessionErrors\x12\x33.descarteslabs.workflows.GetXYZSessionErrorsRequest\x1a!.descarteslabs.workflows.XYZError\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,errors__pb2.DESCRIPTOR,])




_XYZ = _descriptor.Descriptor(
  name='XYZ',
  full_name='descarteslabs.workflows.XYZ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='descarteslabs.workflows.XYZ.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_timestamp', full_name='descarteslabs.workflows.XYZ.created_timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_timestamp', full_name='descarteslabs.workflows.XYZ.updated_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='descarteslabs.workflows.XYZ.name', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='descarteslabs.workflows.XYZ.description', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='descarteslabs.workflows.XYZ.type', index=5,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='descarteslabs.workflows.XYZ.channel', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized_graft', full_name='descarteslabs.workflows.XYZ.serialized_graft', index=7,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized_typespec', full_name='descarteslabs.workflows.XYZ.serialized_typespec', index=8,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='descarteslabs.workflows.XYZ.user', index=9,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org', full_name='descarteslabs.workflows.XYZ.org', index=10,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=322,
)


_CREATEXYZREQUEST = _descriptor.Descriptor(
  name='CreateXYZRequest',
  full_name='descarteslabs.workflows.CreateXYZRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xyz', full_name='descarteslabs.workflows.CreateXYZRequest.xyz', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=385,
)


_GETXYZREQUEST = _descriptor.Descriptor(
  name='GetXYZRequest',
  full_name='descarteslabs.workflows.GetXYZRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xyz_id', full_name='descarteslabs.workflows.GetXYZRequest.xyz_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=418,
)


_GETXYZSESSIONERRORSREQUEST = _descriptor.Descriptor(
  name='GetXYZSessionErrorsRequest',
  full_name='descarteslabs.workflows.GetXYZSessionErrorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xyz_id', full_name='descarteslabs.workflows.GetXYZSessionErrorsRequest.xyz_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='descarteslabs.workflows.GetXYZSessionErrorsRequest.session_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='descarteslabs.workflows.GetXYZSessionErrorsRequest.start_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=509,
)


_XYZERROR = _descriptor.Descriptor(
  name='XYZError',
  full_name='descarteslabs.workflows.XYZError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='descarteslabs.workflows.XYZError.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='descarteslabs.workflows.XYZError.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='descarteslabs.workflows.XYZError.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='descarteslabs.workflows.XYZError.session_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=627,
)

_XYZ.fields_by_name['type'].enum_type = types__pb2._RESULTTYPE
_CREATEXYZREQUEST.fields_by_name['xyz'].message_type = _XYZ
_XYZERROR.fields_by_name['code'].enum_type = errors__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['XYZ'] = _XYZ
DESCRIPTOR.message_types_by_name['CreateXYZRequest'] = _CREATEXYZREQUEST
DESCRIPTOR.message_types_by_name['GetXYZRequest'] = _GETXYZREQUEST
DESCRIPTOR.message_types_by_name['GetXYZSessionErrorsRequest'] = _GETXYZSESSIONERRORSREQUEST
DESCRIPTOR.message_types_by_name['XYZError'] = _XYZERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XYZ = _reflection.GeneratedProtocolMessageType('XYZ', (_message.Message,), dict(
  DESCRIPTOR = _XYZ,
  __module__ = 'xyz_pb2'
  # @@protoc_insertion_point(class_scope:descarteslabs.workflows.XYZ)
  ))
_sym_db.RegisterMessage(XYZ)

CreateXYZRequest = _reflection.GeneratedProtocolMessageType('CreateXYZRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEXYZREQUEST,
  __module__ = 'xyz_pb2'
  # @@protoc_insertion_point(class_scope:descarteslabs.workflows.CreateXYZRequest)
  ))
_sym_db.RegisterMessage(CreateXYZRequest)

GetXYZRequest = _reflection.GeneratedProtocolMessageType('GetXYZRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETXYZREQUEST,
  __module__ = 'xyz_pb2'
  # @@protoc_insertion_point(class_scope:descarteslabs.workflows.GetXYZRequest)
  ))
_sym_db.RegisterMessage(GetXYZRequest)

GetXYZSessionErrorsRequest = _reflection.GeneratedProtocolMessageType('GetXYZSessionErrorsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETXYZSESSIONERRORSREQUEST,
  __module__ = 'xyz_pb2'
  # @@protoc_insertion_point(class_scope:descarteslabs.workflows.GetXYZSessionErrorsRequest)
  ))
_sym_db.RegisterMessage(GetXYZSessionErrorsRequest)

XYZError = _reflection.GeneratedProtocolMessageType('XYZError', (_message.Message,), dict(
  DESCRIPTOR = _XYZERROR,
  __module__ = 'xyz_pb2'
  # @@protoc_insertion_point(class_scope:descarteslabs.workflows.XYZError)
  ))
_sym_db.RegisterMessage(XYZError)



_XYZAPI = _descriptor.ServiceDescriptor(
  name='XYZAPI',
  full_name='descarteslabs.workflows.XYZAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=630,
  serialized_end=923,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateXYZ',
    full_name='descarteslabs.workflows.XYZAPI.CreateXYZ',
    index=0,
    containing_service=None,
    input_type=_CREATEXYZREQUEST,
    output_type=_XYZ,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetXYZ',
    full_name='descarteslabs.workflows.XYZAPI.GetXYZ',
    index=1,
    containing_service=None,
    input_type=_GETXYZREQUEST,
    output_type=_XYZ,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetXYZSessionErrors',
    full_name='descarteslabs.workflows.XYZAPI.GetXYZSessionErrors',
    index=2,
    containing_service=None,
    input_type=_GETXYZSESSIONERRORSREQUEST,
    output_type=_XYZERROR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_XYZAPI)

DESCRIPTOR.services_by_name['XYZAPI'] = _XYZAPI

# @@protoc_insertion_point(module_scope)
