#!/usr/bin/env python

from descarteslabs.services import Raster
import argparse
import json
import base64

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("-keys", default="meta_LC80270312016188_v1", type=str, nargs="+" )
    parser.add_argument("-bands", nargs="+", default=None, type=str)
    parser.add_argument("-scales", default="[[0, 4000], [0, 4000], [0, 4000], [0, 4000]]", type=str)
    parser.add_argument("-resolution", default=240, type=float)
    parser.add_argument("-of", default='GTiff', type=str)
    parser.add_argument("-ot", default='Byte', type=str)
    parser.add_argument("-location", default=None, type=str)

    args = parser.parse_args()

    bands = [eval(b) for b in args.bands] if args.bands else None
    scales = json.loads(args.scales)

    raster = Raster()
    params = {
        'keys': args.keys,
        'bands': bands,
        'scales': scales,
        'resolution': args.resolution,
        'ot': args.ot,
        'of': args.of,
        'location': args.location,
    }
    response = raster.raster(**params)
    for filename, data in response['files'].iteritems():
        with open(filename, "w") as f:
            f.write(base64.b64decode(data))
    print response['metadata']
