# Release the Descartes Labs Python Client to PyPI
name: Publish to PyPI

on:
  # Trigger manually (via Github Web UI)
  workflow_dispatch:
  # Trigger when a Github Release is created
  release:
    types:
      - published
  # Trigger when pushed to this branch
  push:
    branches:
      - infra-2227

jobs:
  publish:
    runs-on: [self-hosted, paas, awscli, docker, ecr-push]
    steps:
      # Checkout the source code from this repository
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Setup the Python environment
      - name: "Setup Python Environment: ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Build the Python wheel packages
      - name: Build Python Packages
        run: |
          pip install twine
          python3 setup.py bdist_wheel
          python3 setup.py sdist

      # Retrieve PyPI upload credentials from Vault into environment variables
      - name: Fetch PyPI Credentials from Vault
        uses: descarteslabs/paas-infrastructure/artifact-sources/github-actions/vault-secret@main
        with:
          secret-path: shared/pypi/descarteslabs-sre
          environment-variable-prefix: TWINE_

      # Upload the Python wheel packages to PyPI
      - name: Upload to PyPI
        run: |
          echo "Would upload these files to PyPI:"
          ls -laR dist

          # NOTE: currently disabled pending code review
          #twine upload -r testpypi dist/*
